routes/web.php
<?php

use function foo\func;
use Symfony\Component\HttpKernel\Fragment\RoutableFragmentRenderer;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('menu', 'MenuController');
Route::get('/', 'HomeController@index')->name('home');

// Route::get('/category', 'CategoryController@index')->name('admin.category');
// Route::get('/product', 'ProductController@index')->name('admin.product')->middleware('admin');
Route::view('/frontt', 'admin.layouts.main');
Route::view('/admin2', 'admin.admin');
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/beverages', 'HomeController@beverages')->name('beverages');
Route::get('/foods', 'HomeController@foods')->name('foods');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/gallery', 'HomeController@gallery')->name('gallery');
Route::get('/gallery/{gallery}', 'HomeController@gallerys')->name('gallerys');
Route::get('/shop', 'HomeController@shop')->name('shop');
Route::get('shops/{product}', 'HomeController@shops')->name('shops');
Route::get('/blog', 'HomeController@blog')->name('blog');
Route::get('blogs/{post}', 'HomeController@blogs')->name('blogs');
Route::resource('/cart', 'CartController');


Route::group(['prefix' => 'admin', 'middleware' => ['admin', 'auth']], function()
{
    Route::resource('product', 'ProductController');
    Route::resource('category', 'CategoryController');
    Route::resource('gallery', 'GalleryController');
    Route::resource('order', 'OrderController');
    Route::resource('post', 'PostController');
    Route::get('dashboard', 'AdminController@index')->name('dashboard');
    Route::post('product/image-upload/{product}', 'ProductController@uploadImages')->name('upload.images');
    Route::post('product/image-destroy/{product}', 'ProductController@destroyImages')->name('destroy.images');
    Route::get('/menuadmin', 'MenuController@index')->name('menus.index');
    Route::view('/galleries', 'admin.galleries');
    Route::get('product/image-upload/{product}','ProductController@upload')->name('product.upload');
    Route::get('orders/{type?}', 'OrderController@Orders')->name('orders.index');
    Route::delete('product/delete/{product}', 'ProductController@delete')->name('product.delete');
 
});

Route::group(['middleware' => 'auth'], function(){
    Route::Resource('address', 'AddressController');  
    Route::get('/checkout/address', 'CheckoutController@address')->name('checkout.address');
    Route::post('/checkout/order', 'CheckoutController@order')->name('checkout.order');
    Route::get('myorder', 'HomeController@myorder')->name('myorder');
    Route::get('invoice/{order}', 'HomeController@invoice')->name('invoice');
    Route::patch('myoder/update-image/{order}' , 'HomeController@updateImages')->name('update.image');
});


Route::get('test', function(){
    // $orders=App\Order::find(2);
    // $new=$orders->user;
    // dd($orders);

    $orders=App\Order::where('user_id', Auth::id())->get();
    // // $new=$orders->user();
    // dd($orders);
    // $user = Auth::user();

    // $orders = self::$user->orders()->orderBy('order_id', 'asc')->get();

    dd($orders);
});

Route::post('/justapage', function() {

    // This is the message that will show in the sweetalert-popup:
    
    Alert::message('Robots are working!');

    // Redirect back to the page you were looking at
    return back();
});

resources/views/front/front2/address.blade.php
@extends('layouts.layout2')

@section('content')
<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url('../front/front2/images/bg-02.jpg');">
    <h2 class="ltext-105 cl0 txt-center">
       Shipping Info
    </h2>
</section>	
<section class="sec-blog bg0 p-t-60 p-b-90">
        <div class="container">

        <div class="col-md-12 col-md-offset-6">
            <h3></h3>
            
                
            <form action="{{route('address.store')}}" method="POST" >
                {{csrf_field()}}
                <div class="form-group">
                    <label for="addressline">Receipt's Name</label>
                    <input type="text" name="receipt" class="form-control">
                </div>
                <div class="form-group">
                    <label for="city">Full Address</label>
                    <input type="text" name="address" class="form-control" >
                </div>
                <div class="form-group">
                    <label for="province">Phone Number</label>
                    <input type="text" name="phone" class="form-control">
                </div>
               
                
                <button type="submit" class="btn btn-info btn-fw">Submit</button>
                
            </form>
        </div>
    </div>
</section>

@endsection

resources/views/front/front2/cart.blade.php
@extends('layouts.layout2')

@section('content')

<!-- Shoping Cart -->
{{-- <form class="bg0 p-t-75 p-b-85" action="" method="post">
    {{csrf_field()}} --}}
<div class="sec-banner bg0 p-t-80 p-b-50" >
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-xl-7 m-lr-auto m-b-50">
                <div class="m-l-25 m-r--38 m-lr-0-xl">
                    <div class="wrap-table-shopping-cart">
                        <table class="table-shopping-cart">
                            <tr class="table_head">
                                <th class="column-1" style="width:100px">Product</th>
                                <th class="column-2"></th>
                                <th class="column-3">Price</th>
                                <th class="column-4">Quantity</th>
                                <th class="column-5">Total</th>
                                <th class="column-6">Action</th>
                            </tr>
                            @foreach($cartItems as $cartItem)
                            <tr class="table_row">
                                <td class="column-1">
                                    
                                    <div class="how-itemcart1">
                                       
                                        <img src="{{$cartItem->options->image}}" alt="IMG">
                                        
                                    </div>
                                   
                                </td>
                                <td class="column-2">{{$cartItem->name}}</td>
                                <td class="column-3">{{$cartItem->price}}</td>
                                <td class="column-4">
                                    {!! Form::open(['route' => ['cart.update', $cartItem->rowId], 'method' => 'PUT' ]) !!} 
                                    <div class="wrap-num-product flex-w m-l-auto m-r-0">
                                        <div class="btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m">
                                            <i class="fs-16 zmdi zmdi-minus"></i>
                                        </div>

                                        <input type="text" name="qty" value="{{$cartItem->qty}}" class="mtext-104 cl3 txt-center num-product" >

                                        <div class="btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m">
                                            <i class="fs-16 zmdi zmdi-plus"></i>
                                        </div>  
                                    </div>
                                </td>
                                <td class="column-5">{{$cartItem->subtotal}}</td>
                                <td class="column-6">
                                    
                                            
                                        {{-- <button type="submit" class="flex-c-m stext-1000 cl5 size-1000 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10">
                                                Update
                                            </button> --}}
                                        <input type="submit" value="Update" class="flex-c-m stext-1000 cl5 size-1000 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10" >
                                    
                                            {!! Form::close() !!}
                                    <div class="form-group">
                                        <form action="{{route('cart.destroy',$cartItem->rowId)}}" method="post">
                                            {{csrf_field()}}
                                            {{method_field('DELETE')}}
                                            <button type="submit" class="flex-c-m stext-1000 cl5 size-1000 bg8 bor13 hov-btn1000 p-lr-15 trans-04 pointer m-tb-10">Delete</button>
                                        </form>
                                        
                                    </div>
                                </td>
                            </tr>
                            @endforeach

                            
                        </table>
                    </div>

                   
                </div>
            </div>
            @foreach($cartItems->take(1) as $cartItem)
            <div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
                <div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
                    <h4 class="mtext-109 cl5 p-b-30">
                        Cart Totals
                    </h4>

                    <div class="flex-w flex-t bor12 p-b-13">
                        <div class="size-208">
                            <span class="stext-110 cl5">
                                Subtotal:
                            </span>
                        </div>

                        <div class="size-209">
                            <span class="mtext-110 cl5">
                               {{Cart::subtotal()}}
                            </span>
                        </div>
                    </div>
                    <div class="flex-w flex-t bor12 p-b-13">
                        <div class="size-208">
                            <span class="stext-110 cl5">
                               Total Items:
                            </span>
                        </div>
    
                        <div class="size-209">
                            <span class="mtext-110 cl5">
                                {{Cart::count()}}
                            </span>
                        </div>
                    </div>

                    <div class="flex-w flex-t bor12 p-t-15 p-b-30">
                        <div class="size-208 w-full-ssm">
                            
                        </div>

                        <div class="size-209 p-r-18 p-r-0-sm w-full-ssm">
                            <p class="stext-111 cl6 p-t-2">
                                
                            </p>
                            
                            
                        </div>
                    </div>

                    <div class="flex-w flex-t p-t-27 p-b-33">
                        <div class="size-208">
                            <span class="mtext-101 cl5">
                                Total:
                            </span>
                        </div>

                        <div class="size-209 p-t-1">
                            <span class="mtext-110 cl5">
                                    {{Cart::total()}}
                            </span>
                        </div>
                    </div>

                    <a href="{{url('/checkout/address')}}"><button class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer">
                        Proceed to Checkout
                    </button></a>
                    
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>
{{-- </form> --}}


@endsection

resources/views/front/front2/gallery.blade.php
@extends('layouts.layout2')
@section('active_gallery', 'active-menu')
@section('content')

<div class="header-lunch parallax0 parallax100" style="background-image: url(&quot;front/front2/images/parallax1.jpg&quot;); background-position: center -20.3333px;">
    <div class="bg1-overlay t-center p-t-100 p-b-100">
            <h2 class="tit4 t-center">Gallery</h2>
    </div>
</div>
<!-- <section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url('front/front2/images/bg-02.jpg');">
    <h2 class="ltext-105 cl0 txt-center">
       Our Gallery
    </h2>
</section>	 -->

<section class="sec-blog bg0 p-t-60 p-b-90">
	<div class="container">
		{{-- <div class="p-b-66">
			<h3 class="ltext-105 cl5 txt-center respon1">
				Our Gallery
			</h3>
		</div> --}}
		<div class="row">
			@foreach($galleries as $gallery)
				<div class="col-sm-6 col-md-4 p-b-40">
					<div class="blog-item">
						<div class="hov-img0">
							<a href="{{asset('images/gallery')}}/{{$gallery->image}}">
								<img style="object-fit: cover;    height: 250px;
									width: 100%;" src="{{asset('images/gallery')}}/{{$gallery->image}}" alt="IMG-BLOG">
							</a>
						</div>
					</div>
				</div>
			@endforeach
		</div>
	</div>
</section>




@endsection

resources/views/front/front2/home.blade.php
@extends('layouts.layout2')
@include('sweetalert::alert')

@section('title', 'Home')
@section('active_home', 'active-menu')

@section('content')

	<!-- Slider -->
	<section class="section-slide">
            <div class="wrap-slick1 rs1-slick1">
                <div class="slick1">
                    <div class="item-slick1" style="background-image: url(front/front2/images/slider4.jpg);">
                        <div class="container h-full">
                            <div class="flex-col-l-m h-full p-t-100 p-b-30">
                                <div class="layer-slick1 animated visible-false" data-appear="fadeInDown" data-delay="0">
                                    <span class="ltext-202 cl2 respon2">
                                        Welcome..
                                    </span>
                                </div>
                                    
                                <div class="layer-slick1 animated visible-false" data-appear="fadeInUp" data-delay="800">
                                    <h2 class="ltext-104 cl2 p-t-19 p-b-43 respon1">
                                        Place For Sharing
                                    </h2>
                                </div>
                                    
                                <!-- <div class="layer-slick1 animated visible-false" data-appear="zoomIn" data-delay="1600">
                                    <a href="{{route('shop')}}" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
                                        Shop Now
                                    </a>
                                </div> -->
                            </div>
                        </div>
                    </div>
    
                    <div class="item-slick1" style="background-image: url(front/front2/images/slider2.jpg);">
                        <div class="container h-full">
                            <div class="flex-col-l-m h-full p-t-100 p-b-30">
                                <div class="layer-slick1 animated visible-false" data-appear="rollIn" data-delay="0">
                                    <span class="ltext-202 cl2 respon2">
                                        Our Special Beans
                                    </span>
                                </div>
                                    
                                <div class="layer-slick1 animated visible-false" data-appear="lightSpeedIn" data-delay="800">
                                    <h2 class="ltext-104 cl2 p-t-19 p-b-43 respon1">
                                        Freshly Roasted
                                    </h2>
                                </div>
                                    
                                <div class="layer-slick1 animated visible-false" data-appear="slideInUp" data-delay="1600">
                                    <a href="{{route('shop')}}" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
                                        Shop Now
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
    
                    <div class="item-slick1" style="background-image: url(front/front2/images/slider3.jpg);">
                        <div class="container h-full">
                            <div class="flex-col-l-m h-full p-t-100 p-b-30">
                                <div class="layer-slick1 animated visible-false" data-appear="rotateInDownLeft" data-delay="0">
                                    <span class="ltext-202 cl2 respon2">
                                        Our Special Story
                                    </span>
                                </div>
                                    
                                <div class="layer-slick1 animated visible-false" data-appear="rotateInUpRight" data-delay="800">
                                    <h2 class="ltext-104 cl2 p-t-19 p-b-43 respon1">
                                        Only For You
                                    </h2>
                                </div>
                                    
                                <div class="layer-slick1 animated visible-false" data-appear="rotateIn" data-delay="1600">
                                    <a href="{{route('blog')}}" class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04">
                                        Read Now
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {{-- <div class="sec-banner bg0 p-t-80 p-b-50" style="background-color: #fffefe">
                <div class="container">
                        <h2 class="tit4 t-center">No Coffee No Work</h2>
                </div>
            </div> --}}
            
    
        <!-- Banner -->
        <div class="sec-banner bg0">
            <div class="flex-w flex-c-m">
                <div class="size-202 m-lr-auto respon4">
                    <!-- Block1 -->
                    <div class="block1 wrap-pic-w">
                        <img src="{{asset('front/front2/images/art-latte2.jpg')}}" alt="IMG-BANNER">
    
                        <a href="{{route('beverages')}}" class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3">
                            <div class="block1-txt-child1 flex-col-l">
                                <span class="block1-name ltext-102 trans-04 p-b-8">
                                    Beverages
                                </span>
    
                                <span class="block1-info stext-102 trans-04">
                                    All Authentic Coffee
                                </span>
                            </div>
    
                            <div class="block1-txt-child2 p-b-4 trans-05">
                                <div class="block1-link stext-101 cl0 trans-09">
                                    Check Now
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
    
                <div class="size-202 m-lr-auto respon4">
                    <!-- Block1 -->
                    <div class="block1 wrap-pic-w">
                        <img src="{{asset('front/front2/images/food2.jpg')}}" alt="IMG-BANNER">
    
                        <a href="{{route('foods')}}" class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3">
                            <div class="block1-txt-child1 flex-col-l">
                                <span class="block1-name ltext-102 trans-04 p-b-8">
                                    Food
                                </span>
    
                                <span class="block1-info stext-102 trans-04">
                                    Good Food Good Mood
                                </span>
                            </div>
    
                            <div class="block1-txt-child2 p-b-4 trans-05">
                                <div class="block1-link stext-101 cl0 trans-09">
                                    Check Now
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
    
                <div class="size-202 m-lr-auto respon4">
                    <!-- Block1 -->
                    <div class="block1 wrap-pic-w">
                        <img src="{{asset('front/front2/images/other2.jpg')}}" alt="IMG-BANNER">
    
                        <a href="{{route('shop')}}" class="block1-txt ab-t-l s-full flex-col-l-sb p-lr-38 p-tb-34 trans-03 respon3">
                            <div class="block1-txt-child1 flex-col-l">
                                <span class="block1-name ltext-102 trans-04 p-b-8">
                                    Our Products
                                </span>
    
                                <span class="block1-info stext-102 trans-04">
                                    New Trend
                                </span>
                            </div>
    
                            <div class="block1-txt-child2 p-b-4 trans-05">
                                <div class="block1-link stext-101 cl0 trans-09">
                                    Shop Now
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    
    
  
        <!-- Product -->
        <section class="sec-product bg0 p-t-100 p-b-50">
             <div class="container">
                <div class="p-b-32">
                    <h3 class="ltext-105 cl5 txt-center respon1">
                        New Products
                    </h3>
                </div>
    
                <div class="flex-w flex-sb-m p-b-52">
                    
    
                    
                  
                    
                </div>
                
                <div class="row isotope-grid">
                        @foreach($products as $product)
                    <div class="col-sm-6 col-md-4 col-lg-3 p-b-35 isotope-item {{$product->category->id}}">
                        <!-- Block2 -->
                        <div class="block2">
                            <div  class="block2-pic hov-img0">
                                @foreach($product->images->take(1) as $image)
                                <img src="{{url($image->image_path)}}" style="object-fit:cover; height:250px; width:100%" alt="IMG-PRODUCT">
                                @endforeach
                                
                            </div>
    
                            <div class="block2-txt flex-w flex-t p-t-14">
                                <div class="block2-txt-child1 flex-col-l ">
                                    <a href="{{url('shops',$product->id)}}" class="stext-104 cl4 hov-cl1 trans-04 js-name-b2 p-b-6">
                                            {{$product->name}}
                                    </a>
    
                                    <span class="stext-105 cl3">
                                            {{$product->price}}
                                    </span>
                                </div>
    
                                <div class="block2-txt-child2 flex-r p-t-3">
                                    <a href="{{route('cart.edit',$product->id )}}" class=" dis-block pos-relative cl5 ">
                                        <i class="zmdi zmdi-shopping-cart c15"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
    
                    @endforeach
                </div>

                
               
            </div>
        </section> 
    
        {{-- <div class="header-lunch parallax0 parallax100" style="background-image: url(&quot;front/front2/images/parallax1.jpg&quot;); background-position: center -20.3333px;">
            <div class="bg1-overlay t-center p-t-170 p-b-165">
                
            </div>
        </div> --}}
        <!-- Blog -->
        <section class="sec-blog bg0 p-t-60 p-b-90">
            <div class="container">
                <div class="p-b-66">
                    <h3 class="ltext-105 cl5 txt-center respon1">
                        Our Blogs
                    </h3>
                </div>
    
                <div class="row">
                    @foreach($posts as $post)
                        <div class="col-sm-6 col-md-4 p-b-40">
                            <div class="blog-item">
                                <div class="hov-img0">
                                    <a href="{{route('blogs', $post->id)}}">
                                        <img style="object-fit: cover;    height: 250px;
                                        width: 100%;" src="{{asset('images/post')}}/{{$post->image}}" alt="IMG-BLOG">
                                    </a>
                                </div>
        
                                <div class="p-t-15">
                                    <div class="stext-107 flex-w p-b-14">
                                        
                                        <span>
                                            <span class="cl4">
                                                on
                                            </span>
        
                                            <span class="cl5">
                                                    {{\Carbon\Carbon::parse($post->created_at)->format('d M Y')}}
                                            </span>
                                        </span>
                                    </div>
        
                                    <h4 class="p-b-12">
                                        <a href="{{route('blogs', $post->id)}}" class="mtext-101 cl5 hov-cl1 trans-04">
                                            {{$post->title}}
                                        </a>
                                    </h4>
        
                                    <p class="stext-108 cl6">
                                        {!!str_limit($post->content, '400', '.....')!!}
                                    </p>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </section>


@endsection

resources/views/front/front2/shops.blade.php
@extends('layouts.layout2')
@section('title', 'Shop')
@section('active_shop', 'active-menu')

@section('content')

<!-- Product Detail -->
    <section class="sec-product-detail bg0 p-t-65 p-b-60">
		<div class="container">
                
			<div class="row">
                    @foreach($products as $product)
				<div class="col-md-6 col-lg-7 p-b-30">
					<div class="p-l-25 p-r-30 p-lr-0-lg">
                            
						<div class="wrap-slick3 flex-sb flex-w">
							<div class="wrap-slick3-dots"></div>
							<div class="wrap-slick3-arrows flex-sb-m flex-w"></div>

							<div class="slick3 gallery-lb">
                                @foreach($product->images as $image)
								<div class="item-slick3" data-thumb="{{url($image->image_path)}}">
									<div class="wrap-pic-w pos-relative">
										<img src="{{url($image->image_path)}}" alt="IMG-PRODUCT">

										<a class="flex-c-m size-108 how-pos1 bor0 fs-16 cl10 bg0 hov-btn3 trans-04" href="{{url($image->image_path)}}">
											<i class="fa fa-expand"></i>
										</a>
									</div>
								</div>
                                @endforeach
								
                            </div>
                            
                        </div>
                        
					</div>
                </div>
                
					
				<div class="col-md-6 col-lg-5 p-b-30">
					<div class="p-r-50 p-t-5 p-lr-0-lg">
						<h4 class="mtext-105 cl5 js-name-detail p-b-14">
							{{$product->name}}
						</h4>

						<span class="mtext-106 cl3">
                                {{$product->price}}
						</span>

						<p class="stext-102 cl3 p-t-23">
                                {!!$product->description!!}
						</p>
						
						<!--  -->
						<div class="p-t-33">
							<div class="flex-w flex-r-m p-b-10">
								<div class="size-204 flex-w flex-m respon6-next">
									<div class="wrap-num-product flex-w m-r-20 m-tb-10">
										<div class="btn-num-product-down cl8 hov-btn3 trans-04 flex-c-m">
											<i class="fs-16 zmdi zmdi-minus"></i>
										</div>

										<input class="mtext-104 cl3 txt-center num-product" type="number" name="qty" value="1">

										<div class="btn-num-product-up cl8 hov-btn3 trans-04 flex-c-m">
											<i class="fs-16 zmdi zmdi-plus"></i>
										</div>
									</div>

									<a href="{{route('cart.edit',$product->id )}}"><button  class="flex-c-m stext-101 cl0 size-101 bg1 bor1 hov-btn1 p-lr-15 trans-04 ">
										Add to cart
									</button></a>
								</div>
							</div>	
						</div>

						<!--  -->
						<div class="flex-w flex-m p-l-100 p-t-40 respon7">
							<div class="flex-m bor9 p-r-10 m-r-11">
								<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 js-addwish-detail tooltip100" data-tooltip="Add to Wishlist">
									<i class="zmdi zmdi-favorite"></i>
								</a>
							</div>

							<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100" data-tooltip="Facebook">
								<i class="fa fa-facebook"></i>
							</a>

							<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100" data-tooltip="Twitter">
								<i class="fa fa-twitter"></i>
							</a>

							<a href="#" class="fs-14 cl3 hov-cl1 trans-04 lh-10 p-lr-5 p-tb-2 m-r-8 tooltip100" data-tooltip="Google Plus">
								<i class="fa fa-google-plus"></i>
							</a>
						</div>
					</div>
                </div>
                @endforeach 
			</div>
            
			
		</div>

		<div class="bg6 flex-c-m flex-w size-302 m-t-73 p-tb-15">
			<span class="stext-107 cl6 p-lr-25">
				
			</span>

			<span class="stext-107 cl6 p-lr-25">
				
			</span>
		</div>
	</section>



@endsection