routes/web.php
<?php

use function foo\func;
use Symfony\Component\HttpKernel\Fragment\RoutableFragmentRenderer;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('menu', 'MenuController');
Route::get('/', 'HomeController@index')->name('home');

// Route::get('/category', 'CategoryController@index')->name('admin.category');
// Route::get('/product', 'ProductController@index')->name('admin.product')->middleware('admin');
Route::view('/frontt', 'admin.layouts.main');
Route::view('/admin2', 'admin.admin');
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/beverages', 'HomeController@beverages')->name('beverages');
Route::get('/foods', 'HomeController@foods')->name('foods');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/gallery', 'HomeController@gallery')->name('gallery');
Route::get('/gallery/{gallery}', 'HomeController@gallerys')->name('gallerys');
Route::get('/shop', 'HomeController@shop')->name('shop');
Route::get('shops/{product}', 'HomeController@shops')->name('shops');
Route::get('/blog', 'HomeController@blog')->name('blog');
Route::get('blogs/{post}', 'HomeController@blogs')->name('blogs');
Route::resource('/cart', 'CartController');


Route::group(['prefix' => 'admin', 'middleware' => ['admin', 'auth']], function()
{
    Route::resource('product', 'ProductController');
    Route::resource('category', 'CategoryController');
    Route::resource('gallery', 'GalleryController');
    Route::resource('order', 'OrderController');
    Route::resource('post', 'PostController');
    Route::get('dashboard', 'AdminController@index')->name('dashboard');
    Route::post('product/image-upload/{product}', 'ProductController@uploadImages')->name('upload.images');
    Route::post('product/image-destroy/{product}', 'ProductController@destroyImages')->name('destroy.images');
    Route::get('/menuadmin', 'MenuController@index')->name('menus.index');
    Route::view('/galleries', 'admin.galleries');
    Route::get('product/image-upload/{product}','ProductController@upload')->name('product.upload');
    Route::get('orders/{type?}', 'OrderController@Orders')->name('orders.index');
    Route::delete('product/delete/{product}', 'ProductController@delete')->name('product.delete');
 
});

Route::group(['middleware' => 'auth'], function(){
    Route::Resource('address', 'AddressController');  
    Route::get('/checkout/address', 'CheckoutController@address')->name('checkout.address');
    Route::post('/checkout/order', 'CheckoutController@order')->name('checkout.order');
    Route::get('myorder', 'HomeController@myorder')->name('myorder');
    Route::get('invoice/{order}', 'HomeController@invoice')->name('invoice');
    Route::patch('myoder/update-image/{order}' , 'HomeController@updateImages')->name('update.image');
});


Route::get('test', function(){
    // $orders=App\Order::find(2);
    // $new=$orders->user;
    // dd($orders);

    $orders=App\Order::where('user_id', Auth::id())->get();
    // // $new=$orders->user();
    // dd($orders);
    // $user = Auth::user();

    // $orders = self::$user->orders()->orderBy('order_id', 'asc')->get();

    dd($orders);
});

Route::post('/justapage', function() {

    // This is the message that will show in the sweetalert-popup:
    
    Alert::message('Robots are working!');

    // Redirect back to the page you were looking at
    return back();
});

resources/views/admin/catMenu.blade.php
@extends('admin.layouts.main')

@section('content')

<script>
 
</script>


<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h3 >Category</h3>
            <br>
            <button class="btn btn-success btn-fw" data-toggle="modal" data-target="#exampleModal">New Category<i class="mdi mdi-plus"></i></button>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-md" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Add New Category</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                        <!--============ modal body =========--> 
                            <div class="col-md-12  grid-margin stretch-card">
                                <div class="card">
                                    <div class="card-body">
                                        <h4 class="card-title"></h4>
                                        <p class="card-description"></p>
                                            <form action="{{route('catmenu.store')}}" method="post">
                                                {{csrf_field()}}
                                            
                                            <div class="form-group">
                                                <label for="name">Category Name</label>
                                                <input type="text" class="form-control" id="cat_name" name="cat_name" placeholder="Name">
                                            </div>
                                            <input type="submit" class="btn btn-success mr-2"> >
                                                <button class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                            </form>
                                    </div>
                                </div>
                            </div>
                        <!--============ /modal body =========--> 
                        </div>
                    </div>
                </div>
            </div>


            <div class="table-responsive">
                <table class="table table-striped" >
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Category</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($categories as $category)
                        <tr>
                            <td>{{$category->id}} </td>
                            <td> {{$category->name}} </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/admin/category.blade.php
@extends('admin.layouts.main')

@section('content')

<script>
 
</script>


<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <h3 >Category</h3>
      <br>
      <button class="btn btn-success btn-fw" data-toggle="modal" data-target="#exampleModal">New Category<i class="mdi mdi-plus"></i></button>
      <!-- Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-md" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Add New Category</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
              <!--============ modal body =========--> 
              <div class="col-md-12  grid-margin stretch-card">
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title"></h4>
                    <p class="card-description"></p>
                    <form action="{{route('category.store')}}" method="post">
                      {{csrf_field()}}
                      <div class="form-group">
                        <label for="name">Category Name</label>
                          <input type="text" class="form-control" id="cat_name" name="cat_name" placeholder="Name">
                      </div>
                      <input type="submit" class="btn btn-success mr-2"> >
                      <button class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    </form>
                  </div>
                </div>
              </div>
              <!--============ /modal body =========--> 
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Drinks</h3>
        <br>
        <div class="table-responsive">
          <table class="table table-striped" >
            <thead>
              <tr>
                <th>No.</th>
                <th>Name</th>
              </tr>
            </thead>
            <tbody>
              @foreach($drinks as $key=>$drink)
              <tr>
                <td>{{++$key}}</td>
                <td>{{$drink->name}}</td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Foods</h3>
          <br>
          <div class="table-responsive">
            <table class="table table-striped" >
              <thead>
                <tr>
                  <th>No.</th>
                  <th>Name</th>
                </tr>
              </thead>
              <tbody>
                @foreach($foods as $key=>$food)
                <tr>
                  <td>{{++$key}} </td>
                  <td>{{$food->name}}</td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
    <div class="col-lg-6 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Products</h3>
          <br>
          <div class="table-responsive">
            <table class="table table-striped" >
              <thead>
                <tr>
                  <th>No.</th>
                  <th>Name</th>
                </tr>
              </thead>
              <tbody>
                @foreach($products as $key=>$product)
                <tr>
                  <td>{{++$key}}</td>
                  <td>{{$product->name}}</td>
                </tr>
                @endforeach
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
</div>






      
@endsection

resources/views/admin/justapage.blade.php
@extends('admin.layouts.main')

@section('content')

<form action="/justapage" method="post">
    {{ csrf_field() }}
    <button type="submit">Click me!</button>
</form>

@endsection

resources/views/admin/menuadmin.blade.php
@extends('admin.layouts.main')
@section('title', 'Menu')
@section('content')


<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Add Menu</h4>
                <button class="btn btn-success btn-fw" data-toggle="modal" data-target="#exampleModal">New Menu
                        <i class="mdi mdi-plus"></i>
                </button>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Add New Menu</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <!--============ modal body =========--> 
                                <div class="col-md-12  grid-margin stretch-card">
                                    <div class="card">
                                        <div class="card-body">
                                            <h4 class="card-title"></h4>
                                            <p class="card-description"></p>
                                            
                                        <form action="{{route('menu.store')}}" method="post">
                                                {{csrf_field()}}
                                                <div class="form-group">
                                                    <label for="name">Name</label>
                                                    <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                                                </div>
                                                <div class="form-group">
                                                    <label for="category">Category</label>
                                                    <select class="form-control" id="category_id" name="category_id">
                                                    <option >Please Select Category</option>
                                                        @foreach($categories as $category)
                                                            <option value="{{$category->id}}">{{$category->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                                <div class="form-group">
                                                    <label for="price">Price</label>
                                                    <input type="text" class="form-control" id="price" name="price" placeholder="Price">
                                                </div>
                                                <div class="form-group">
                                                    <label for="description">Description</label>
                                                    <textarea class="form-control" id="description" name="description" rows="3"></textarea>
                                                </div>
                                                <input type="submit" id="btnmodal" class="btn btn-success mr-2"> 
                                            </form>
                                            
                                        </div>
                                    </div>
                                </div>

                            <!--============ /modal body =========--> 
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Coffee</h3>
                <br>
                <div class="table-responsive">
                    <table class="table table-striped" >
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Description</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach($coffees as $key=>$coffee)
                            <tr>
                                <td>{{++$key}} </td>
                                <td>{{$coffee->name}}</td>
                                <td>{{$coffee->price}}</td>
                                <td>{{$coffee->description}}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Manula Brew</h3>
                    <br>
                    <div class="table-responsive">
                        <table class="table table-striped" >
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Name</th>
                                    <th>Price</th>
                                    <th>Description</th>
    
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($manualbrews as  $key=>$manualbrew)
                                <tr>
                                    <td>{{++$key}}</td>
                                    <td>{{$manualbrew->name}}</td>
                                    <td>{{$manualbrew->price}}</td>
                                    <td>{{$manualbrew->description}}</td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
</div>

<div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Other</h3>
                    <br>
                    <div class="table-responsive">
                        <table class="table table-striped" >
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Name</th>
                                    <th>Price</th>
                                    <th>Description</th>
    
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($others as $key=>$other)
                                <tr>
                                    <td>{{++$key }}</td>
                                    <td>{{$other->name}}</td>
                                    <td>{{$other->price}}</td>
                                    <td>{{$other->description}}</td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
</div>





<div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Main Course</h3>
                    <br>
                    <div class="table-responsive">
                        <table class="table table-striped" >
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Name</th>
                                    <th>Price</th>
                                    <th>Description</th>
    
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($mains as $key=>$main)
                                <tr>
                                    <td>{{++$key}}</td>
                                    <td>{{$main->name}}</td>
                                    <td>{{$main->price}}</td>
                                    <td>{{$main->description}}</td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
</div>

<div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Dessert</h3>
                    <br>
                    <div class="table-responsive">
                        <table class="table table-striped" >
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Name</th>
                                    <th>Price</th>
                                    <th>Description</th>
    
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($desserts as $key=>$dessert)
                                <tr>
                                    <td>{{++$key}}</td>
                                    <td>{{$dessert->name}}</td>
                                    <td>{{$dessert->price}}</td>
                                    <td>{{$dessert->description}}</td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
</div>

    
@endsection

resources/views/admin/order.blade.php
@extends('admin.layouts.main')
@section('title', 'Order')
@section('content')

<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Order ID</th>
                                <th>Total</th>
                                <th>Invoice</th>
                                <th>Transfer Pict</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($orders as $order)
                            <tr>
                                <td>{{$order->user->name}}</td>
                                <td>INV{{$order->id}}</td>
                                <td>{{$order->total}}</td>
                                <td><a href="{{route('order.update',$order->id)}}"><img style="width:100px; height:100px" src="{{asset('images/transfer/invoice.png')}}" alt=""></a></td>
                                <td>
                                    <div class="item-slick3" data-thumb="{{asset('images/transfer')}}/{{$order->image}}">
                                    <div class="wrap-pic-w pos-relative">
                                            <a class="flex-c-m size-108 how-pos1 bor0 fs-16 cl10 bg0 hov-btn3 trans-04" href="{{asset('images/transfer')}}/{{$order->image}}">
                                                <img style="width:100px; height:100px" src="{{asset('images/transfer')}}/{{$order->image}}" alt="IMG-PRODUCT">
                                            
                                                
                                            </a>
                                    </div>
                                    </div>
                                </td>
                                <td>
                                    <label class=" <?php if($order->status == 0){
                                            echo "badge badge-danger";
                                        } elseif($order->status == 1){
                                            echo "badge badge-warning";
                                        } else {
                                            "";
                                        } ?>
                                        <?php if($order->status == 2){
                                            echo "badge badge-success";
                                        } ?>
                                        ">
                                        <?php if($order->status == 0){
                                            echo "Unpaid";
                                        } elseif($order->status == 1){
                                            echo "Processing";
                                        } else {
                                            echo "";
                                        } ?>
                                        
                                        <?php if($order->status == 2){
                                            echo "Delivered";
                                        } ?>
                                    </label>
                                </td>
                                <td style="width:200px">
                                    {!! Form::open(['route' => ['order.update', $order->id], 'method' => 'PUT' ]) !!} 
                                    
                                    <div class="form-group">
                                        <select name="status" class="form-control" aria-placeholder="Select Action" >
                                                <option  disabled selected hidden>Please Select Action</option>
                                                <option name="status" value="0">Unpaid</option>
                                                <option name="status"  value="1">Processing</option>
                                                <option name="status"  value="2">Delivered</option>
                                        </select>
                                        <input type="submit" value="OK" class="btn btn-info btn-block">
                                    </div>
                                    <div class="form-group">
                                        
                                    </div>
                                    {{-- <div><a href="" class="btn btn-success">Ok</a></div> --}}
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection