routes/web.php
<?php

use function foo\func;
use Symfony\Component\HttpKernel\Fragment\RoutableFragmentRenderer;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('menu', 'MenuController');
Route::get('/', 'HomeController@index')->name('home');

// Route::get('/category', 'CategoryController@index')->name('admin.category');
// Route::get('/product', 'ProductController@index')->name('admin.product')->middleware('admin');
Route::view('/frontt', 'admin.layouts.main');
Route::view('/admin2', 'admin.admin');
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/beverages', 'HomeController@beverages')->name('beverages');
Route::get('/foods', 'HomeController@foods')->name('foods');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/gallery', 'HomeController@gallery')->name('gallery');
Route::get('/gallery/{gallery}', 'HomeController@gallerys')->name('gallerys');
Route::get('/shop', 'HomeController@shop')->name('shop');
Route::get('shops/{product}', 'HomeController@shops')->name('shops');
Route::get('/blog', 'HomeController@blog')->name('blog');
Route::get('blogs/{post}', 'HomeController@blogs')->name('blogs');
Route::resource('/cart', 'CartController');


Route::group(['prefix' => 'admin', 'middleware' => ['admin', 'auth']], function()
{
    Route::resource('product', 'ProductController');
    Route::resource('category', 'CategoryController');
    Route::resource('gallery', 'GalleryController');
    Route::resource('order', 'OrderController');
    Route::resource('post', 'PostController');
    Route::get('dashboard', 'AdminController@index')->name('dashboard');
    Route::post('product/image-upload/{product}', 'ProductController@uploadImages')->name('upload.images');
    Route::post('product/image-destroy/{product}', 'ProductController@destroyImages')->name('destroy.images');
    Route::get('/menuadmin', 'MenuController@index')->name('menus.index');
    Route::view('/galleries', 'admin.galleries');
    Route::get('product/image-upload/{product}','ProductController@upload')->name('product.upload');
    Route::get('orders/{type?}', 'OrderController@Orders')->name('orders.index');
    Route::delete('product/delete/{product}', 'ProductController@delete')->name('product.delete');
 
});

Route::group(['middleware' => 'auth'], function(){
    Route::Resource('address', 'AddressController');  
    Route::get('/checkout/address', 'CheckoutController@address')->name('checkout.address');
    Route::post('/checkout/order', 'CheckoutController@order')->name('checkout.order');
    Route::get('myorder', 'HomeController@myorder')->name('myorder');
    Route::get('invoice/{order}', 'HomeController@invoice')->name('invoice');
    Route::patch('myoder/update-image/{order}' , 'HomeController@updateImages')->name('update.image');
});


Route::get('test', function(){
    // $orders=App\Order::find(2);
    // $new=$orders->user;
    // dd($orders);

    $orders=App\Order::where('user_id', Auth::id())->get();
    // // $new=$orders->user();
    // dd($orders);
    // $user = Auth::user();

    // $orders = self::$user->orders()->orderBy('order_id', 'asc')->get();

    dd($orders);
});

Route::post('/justapage', function() {

    // This is the message that will show in the sweetalert-popup:
    
    Alert::message('Robots are working!');

    // Redirect back to the page you were looking at
    return back();
});

resources/views/admin/layouts/partials/footer.blade.php
<footer class="footer">
          <div class="container-fluid clearfix">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2018
              <a href="http://www.bootstrapdash.com/" target="_blank">Rumah Seduh</a>. All rights reserved.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Speciality Coffee
              <i class="mdi mdi-heart text-danger"></i>
            </span>
          </div>
        </footer>

resources/views/admin/layouts/partials/navbar.blade.php
<nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
        <a class="navbar-brand brand-logo" href="index.html">
          <img style="height:50px; width:158px" src="{{asset('front/front2/images/icons/coffee-logo.png')}}" alt="logo" />
        </a>
        <a class="navbar-brand brand-logo-mini" href="index.html">
          <img src="{{asset('admin/images/logo-mini.svg')}}" alt="logo" />
        </a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center">
        
        <ul class="navbar-nav navbar-nav-right">
          {{-- <li class="nav-item dropdown">
            <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <i class="mdi mdi-file-document-box"></i>
              <span class="count">7</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="messageDropdown">
              <div class="dropdown-item">
                <p class="mb-0 font-weight-normal float-left">You have 7 unread mails
                </p>
                <span class="badge badge-info badge-pill float-right">View all</span>
              </div>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <img src="{{asset('admin/images/faces/face4.jpg')}}" alt="image" class="profile-pic">
                </div>
                <div class="preview-item-content flex-grow">
                  <h6 class="preview-subject ellipsis font-weight-medium text-dark">David Grey
                    <span class="float-right font-weight-light small-text">1 Minutes ago</span>
                  </h6>
                  <p class="font-weight-light small-text">
                    The meeting is cancelled
                  </p>
                </div>
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <img src="{{asset('admin/images/faces/face2.jpg')}}" alt="image" class="profile-pic">
                </div>
                <div class="preview-item-content flex-grow">
                  <h6 class="preview-subject ellipsis font-weight-medium text-dark">Tim Cook
                    <span class="float-right font-weight-light small-text">15 Minutes ago</span>
                  </h6>
                  <p class="font-weight-light small-text">
                    New product launch
                  </p>
                </div>
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <img src="{{asset('admin/images/faces/face3.jpg')}}" alt="image" class="profile-pic">
                </div>
                <div class="preview-item-content flex-grow">
                  <h6 class="preview-subject ellipsis font-weight-medium text-dark"> Johnson
                    <span class="float-right font-weight-light small-text">18 Minutes ago</span>
                  </h6>
                  <p class="font-weight-light small-text">
                    Upcoming board meeting
                  </p>
                </div>
              </a>
            </div>
          </li> --}}
          {{-- <li class="nav-item dropdown">
            <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
              <i class="mdi mdi-bell"></i>
              <span class="count">4</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
              <a class="dropdown-item">
                <p class="mb-0 font-weight-normal float-left">You have 4 new notifications
                </p>
                <span class="badge badge-pill badge-warning float-right">View all</span>
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-success">
                    <i class="mdi mdi-alert-circle-outline mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-medium text-dark">Application Error</h6>
                  <p class="font-weight-light small-text">
                    Just now
                  </p>
                </div>
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-warning">
                    <i class="mdi mdi-comment-text-outline mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-medium text-dark">Settings</h6>
                  <p class="font-weight-light small-text">
                    Private message
                  </p>
                </div>
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-info">
                    <i class="mdi mdi-email-outline mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-medium text-dark">New user registration</h6>
                  <p class="font-weight-light small-text">
                    2 days ago
                  </p>
                </div>
              </a>
            </div>
          </li> --}}
          <li class="nav-item dropdown d-none d-xl-inline-block">
            <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <span class="profile-text">Hello, {{ Auth::user()->name }} !</span>
              <img class="img-xs rounded-circle" style="" src="{{asset('admin/images/faces/face1.jpg')}}" alt="Profile image">
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              {{-- <a class="dropdown-item p-0">
                <div class="d-flex border-bottom">
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                    <i class="mdi mdi-bookmark-plus-outline mr-0 text-gray"></i>
                  </div>
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center border-left border-right">
                    <i class="mdi mdi-account-outline mr-0 text-gray"></i>
                  </div>
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                    <i class="mdi mdi-alarm-check mr-0 text-gray"></i>
                  </div>
                </div>
              </a> --}}
              <a class="dropdown-item">
                
              </a>
              <a class="dropdown-item" href="{{route('home')}}" >
                Front End 
              </a>
              
                <a class="dropdown-item" href="{{ route('logout') }}"
                    onclick="event.preventDefault();
										document.getElementById('logout-form').submit();">
                  Sign Out
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" >
                  {{ csrf_field() }}
                </form>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>

resources/views/admin/layouts/partials/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item nav-profile">
            <div class="nav-link">
              {{-- <div class="user-wrapper">
                <div class="profile-image">
                  <img src="{{asset('front/front2/images/icons/coffee-logo.png')}}" alt="profile image">
                </div>
                <div class="text-wrapper">
                  <p class="profile-name">Coffee.co</p>
                  <div>
                    <small class="designation text-muted">Admin</small>
                    <span class="status-indicator online"></span>
                  </div>
                </div>
              </div> --}}
              
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{route('dashboard')}}">
              <i class="menu-icon mdi mdi-television"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{route('post.index')}}">
              <i class="menu-icon mdi mdi-library-books"></i>
              <span class="menu-title">Post Article</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{route('product.index')}}">
              <i class="menu-icon mdi mdi-wallet-travel"></i>
              <span class="menu-title">Products</span>
            </a>
          </li>
          {{-- <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic2" aria-expanded="false" aria-controls="ui-basic2" >
              <i class="menu-icon mdi mdi-wallet-travel"></i>
              <span class="menu-title">Products</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-basic2">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item">
                    <a class="nav-link" href="{{route('category.index')}}">Category</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{{route('product.index')}}">Add Product</a>
                    </li>
                </ul>
              </div>
          </li> --}}
          <li class="nav-item">
            <a class="nav-link" href="{{url('admin/orders')}}">
              <i class="menu-icon mdi mdi-chart-line"></i>
              <span class="menu-title">Orders</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{route('menus.index')}}">
              <i class="menu-icon mdi mdi-table"></i>
              <span class="menu-title">Menus</span>
            </a>
          </li>
          {{-- <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic3" aria-expanded="false" aria-controls="ui-basic">
              <i class="menu-icon mdi mdi-table"></i>
              <span class="menu-title">Menus</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-basic3">
                <ul class="nav flex-column sub-menu">
                  <li class="nav-item">
                    <a class="nav-link" href="{{url('/catmenu')}}">Category Menus</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{{route('menus.index')}}">Add Menu</a>
                    </li>
                </ul>
              </div>
          </li> --}}
          <li class="nav-item">
            <a class="nav-link" href="{{route('gallery.index')}}">
              <i class="menu-icon mdi mdi-image-multiple"></i>
              <span class="menu-title">Galleries</span>
            </a>
          </li>
          
        </ul>
      </nav>

resources/views/admin/layouts/partials/tinymce.blade.php
<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>
<script>
    tinymce.init({
        selector: 'textarea'
    });
</script>