routes/web.php
<?php

use function foo\func;
use Symfony\Component\HttpKernel\Fragment\RoutableFragmentRenderer;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::resource('menu', 'MenuController');
Route::get('/', 'HomeController@index')->name('home');

// Route::get('/category', 'CategoryController@index')->name('admin.category');
// Route::get('/product', 'ProductController@index')->name('admin.product')->middleware('admin');
Route::view('/frontt', 'admin.layouts.main');
Route::view('/admin2', 'admin.admin');
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/beverages', 'HomeController@beverages')->name('beverages');
Route::get('/foods', 'HomeController@foods')->name('foods');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/gallery', 'HomeController@gallery')->name('gallery');
Route::get('/gallery/{gallery}', 'HomeController@gallerys')->name('gallerys');
Route::get('/shop', 'HomeController@shop')->name('shop');
Route::get('shops/{product}', 'HomeController@shops')->name('shops');
Route::get('/blog', 'HomeController@blog')->name('blog');
Route::get('blogs/{post}', 'HomeController@blogs')->name('blogs');
Route::resource('/cart', 'CartController');


Route::group(['prefix' => 'admin', 'middleware' => ['admin', 'auth']], function()
{
    Route::resource('product', 'ProductController');
    Route::resource('category', 'CategoryController');
    Route::resource('gallery', 'GalleryController');
    Route::resource('order', 'OrderController');
    Route::resource('post', 'PostController');
    Route::get('dashboard', 'AdminController@index')->name('dashboard');
    Route::post('product/image-upload/{product}', 'ProductController@uploadImages')->name('upload.images');
    Route::post('product/image-destroy/{product}', 'ProductController@destroyImages')->name('destroy.images');
    Route::get('/menuadmin', 'MenuController@index')->name('menus.index');
    Route::view('/galleries', 'admin.galleries');
    Route::get('product/image-upload/{product}','ProductController@upload')->name('product.upload');
    Route::get('orders/{type?}', 'OrderController@Orders')->name('orders.index');
    Route::delete('product/delete/{product}', 'ProductController@delete')->name('product.delete');
 
});

Route::group(['middleware' => 'auth'], function(){
    Route::Resource('address', 'AddressController');  
    Route::get('/checkout/address', 'CheckoutController@address')->name('checkout.address');
    Route::post('/checkout/order', 'CheckoutController@order')->name('checkout.order');
    Route::get('myorder', 'HomeController@myorder')->name('myorder');
    Route::get('invoice/{order}', 'HomeController@invoice')->name('invoice');
    Route::patch('myoder/update-image/{order}' , 'HomeController@updateImages')->name('update.image');
});


Route::get('test', function(){
    // $orders=App\Order::find(2);
    // $new=$orders->user;
    // dd($orders);

    $orders=App\Order::where('user_id', Auth::id())->get();
    // // $new=$orders->user();
    // dd($orders);
    // $user = Auth::user();

    // $orders = self::$user->orders()->orderBy('order_id', 'asc')->get();

    dd($orders);
});

Route::post('/justapage', function() {

    // This is the message that will show in the sweetalert-popup:
    
    Alert::message('Robots are working!');

    // Redirect back to the page you were looking at
    return back();
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name', 'category_id', 'price', 'image', 'description'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function images()
    {
        return $this->hasMany(ProductImage::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\ProductImage;
use App\Category;
Use Alert;
use Illuminate\Http\Request;
use PhpParser\Node\Stmt\Return_;




class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        $categories = Category::whereIn('id', [7,8])->get();
        $images = ProductImage::where('product_id');
       
        
        return view('admin.products.index', compact(['products', 'categories']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::all();
        $categories = Category::whereIn('id', [7,8])->get();

        return view('admin.products.create', compact(['products', 'categories']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate(request(),[
            'name' => 'required',
            'category_id' => 'required',
            'price' => 'required',
            'description' => 'required'
        ]);

        $post= Product::create([
            'name' => request('name'),
            'category_id' => request('category_id'),
            'price' => request('price'),
            'description' => request('description'),
            'image' => "img.jpg"
        ]);

        if($post){
            alert()->success('Post Created', 'Successfully');
            return redirect()->route('product.index');
        }

        

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    
    
    
    
    public function uploadImages(Product $product , Request $request)
    {
        $products = Product::find($product);

        $image=$request->file('file');

        if($image)
        {
            $imageName=$image->getClientOriginalName();
            $image->move('images', $imageName);

            $imagePath= ("images/$imageName");
            $product->images()->create(['image_path'=>$imagePath]);
        }

        return "Success";
    }
    
    public function destroyImages($product)
    {
        $file = Product::find($product);
        $files= $file->images;
        dd($filename[0]->image_path);



    //    $filename = $request->id;
    //    $uploaded_image = ProductImage::where('id')
        // $filename = Product::find($product);
        // $image=$request->file('file');
        // $uploaded_image = ProductImage::where('product_id', basename($filename))->first();
 
        // if (empty($uploaded_image)) {
        //     return Response::json(['message' => 'Sorry file does not exist'], 400);
        // }
 
        // $file_path = ("$uploaded_image");
        
        // if (file_exists($file_path)) {
        //     unlink($file_path);
        // }
 
        // if (file_exists($resized_file)) {
        //     unlink($resized_file);
        // }
 
        // if (!empty($uploaded_image)) {
        //     $uploaded_image->delete();
        // }
 
        // return Response::json(['message' => 'File successfully delete'], 200);
        

        // return "image hass been removed";
    }
    // public function invoice($order)
    // {
    //     $orders=Order::where('id', $order)->get();
    //     // $users=Order::where('id', $order)->get(['user_id'])->first();
    //     // // $user=$users->user_id;
    //     // dd($users);
    //     // $addresses=Address::where('user_id', $users)->get();
    //     $cartItems = Cart::content();
    //     return view('front.front2.invoice', compact(['cartItems', 'orders', 'users', 'addresses']));
    // }
    
     public function show($product)
    {
        $orders=Order::where('id', $order)->get();
        $cartItems = Cart::content();
        return view('admin.invoice', compact(['cartItems', 'orders', 'users', 'addresses']));
    
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $posts = Product::find($product);

        return view('admin.products.edit', compact('products'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $formInput = $request->except('image');
        
        $this->validate($request,[
            'name' => 'required',
            'category_id' => 'required',
            'price' => 'required',
            'description' => 'required'
        ]);


        $image = $request->image;
        
        if($image)
        {
            $filename = $image->getClientOriginalName();
            $image->move('images/product', $filename);
            $formInput['image'] = $filename;
            
        }
        $product->update($formInput,[
            'name' => request('name'),
            'category_id' => request('category_id'),
            'price' => request('price'),
            'description' => request('description'),
            
        ]);
        Alert::success('Product Edited!', 'Success');
        return redirect()->route('product.index');  
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($product)
    {
        // $file = Product::where('id', $product)->get();
        $file = ProductImage::find($product);
        $files= $file->image_path;
        // $imagepath = $file->image_path;
        // dd($files);
        // ProductImage::delete($files);
        if($file){
            return $file->delete($files);
        }
        // if(ProductImage::exists($files)){
        //     ProductImage::delete($files);
        // }
        return "deleted";
        
    }

    public function delete(Product $product)
    {
        $product->delete();
        Alert::success('Product Deleted!', 'Success');
        return redirect()->route('product.index');
    }
}

resources/views/admin/products/create.blade.php
@extends('admin.layouts.main')
@section('title', 'Create Products')
@section('tinymce')
    @include('admin.layouts.partials.tinymce')
@endsection
@include('sweetalert::alert')

@section('content')
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">New Product</h4>
                <p class="card-description"></p>
                    <form action="{{route('product.store')}}" method="post">
                        {{csrf_field()}}
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                        </div>
                        <div class="form-group">
                            <label for="category">Category</label>
                            <select class="form-control" id="category_id" name="category_id">
                            <option >Please Select Category</option>
                            @foreach($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="price">Price</label>
                            <input type="text" class="form-control" id="price" name="price" placeholder="Price">
                        </div>

                        
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea class="form-control" id="description" name="description" rows="3"></textarea>
                        </div>

                        
                        <input type="submit" id="btnmodal" class="btn btn-success mr-2"> 
                    </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/products/edit.blade.php
<!-- @extends('admin.layouts.main')
@section('title', 'Create Products')
@section('tinymce')
    @include('admin.layouts.partials.tinymce')
@endsection
@include('sweetalert::alert')

@section('content')
<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">New Product</h4>
                <p class="card-description"></p>
                    <form action="{{route('product.update', $product->id)}}" method="post">
                        {{csrf_field()}}
                        {{method_field('PATCH')}}
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" value= "{{$product->name}}"class="form-control" id="name" name="name" placeholder="Name">
                        </div>
                        <div class="form-group">
                            <label for="category">Category</label>
                            <select class="form-control" id="category_id" name="category_id">
                            <option >Please Select Category</option>
                            @foreach($categories as $category)
                            <option value="{{$product->$category->id}}">{{$category->name}}</option>
                            @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="price">Price</label>
                            <input type="text" value= "{{$products->name}}"class="form-control" id="price" name="price" placeholder="Price">
                        </div>

                        
                        <div class="form-group">
                            <label for="description">Description</label>
                            <textarea class="form-control" value= "{{$products->description}}"id="description" name="description" rows="3"></textarea>
                        </div>

                        
                        <input type="submit" id="btnmodal" class="btn btn-success mr-2"> 
                    </form>
            </div>
        </div>
    </div>
</div>

@endsection -->

resources/views/admin/products/index.blade.php
@extends('admin.layouts.main')
@section('title', 'Products')
@include('sweetalert::alert')

@section('content')



<div class="col-lg-12 grid-margin stretch-card">
  <div class="card">
    <div class="card-body">
      <h3>
        <a href="{{route('product.create')}}">
          <button class="btn btn-success btn-fw" data-toggle="modal" data-target="#exampleModal">New Product
          <i class="mdi mdi-plus"></i></button>
        </a> 
      </h3>
      <br>
      <div class="table-responsive">
        <table class="table table-striped" >
          <thead>
            <tr>
              <th>No.</th>
              <th>Product</th>
              <th>Price</th>
              <th>Category</th>
              <th>Image</th>
              <th>Description</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            @foreach($products as $key=>$product)
            <tr>
              <td style="width:50px">{{++$key}}</td>
              <td style="white-space: -o-pre-wrap; 
              word-wrap: break-word;
              white-space: pre-wrap; 
              white-space: -moz-pre-wrap; 
              white-space: -pre-wrap; width:300px" >{{$product->name}}</td>
              <td>Rp. {{$product->price}}</td>
              <td>{{$product->category->name}}</td>
              <td  style="width:350px">
                <div class="row">
                  @foreach($product->images as $image)
                    <div class="item-slick3" data-thumb="{{url($image->image_path)}}">
                      <div class="wrap-pic-w pos-relative">
                        <a class="flex-c-m size-108 how-pos1 bor0 fs-16 cl10 bg0 hov-btn3 trans-04" href="{{url($image->image_path)}}">
                          <img style="height:50px; width:50px" src="{{url($image->image_path)}}" alt="IMG-PRODUCT">
                        </a>
                      </div>
                    </div>
                    {{-- <img style="height:50px; width:50px" src="{{url($image->image_path)}}" alt="image" /> --}}
                      <form action="{{route('product.destroy', $image->id)}}" method="POST" enctype="multipart/form-data">
                          {{csrf_field()}}
                          {{method_field('DELETE')}}  
                        <button type="submit"><a href=""><i class="mdi mdi-delete"></i></a></button>
                      </form>
                      <br>
                  @endforeach
                </div>
                <br>
                
                <div class="row">
                  <button type="button" class="btn btn-outline-info btn-fw" data-toggle="modal" data-target="#upload-image-{{$product->id}}" data-item-id="{{$product->id}}">
                    <i class="mdi mdi-upload"></i>Upload
                  </button>
                  <!-- Modal -->
                  <div class="modal fade" id="upload-image-{{$product->id}}" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="uploadModalLabel">Add New Product</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                        <!--============ modal body =========--> 
                          <div class="col-md-12  grid-margin stretch-card">
                            <div class="card">
                              <div class="card-body">
                                <h4 class="card-title"></h4>
                                <p class="card-description"></p>
                                  <form action="{{route('upload.images', $product->id)}}" method="post" class="dropzone" id="my-awesome-dropzone-{{$product->id}}">
                                      {{csrf_field()}}
                                    <input type="file" name="file" >
                                  </form>
                                <button type="submit" id="btnmodal" class="btn btn-success mr-2"> </button>
                              </div>
                            </div>
                          </div>

                          <!--============ /modal body =========--> 
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </td>
              <td style="white-space: -o-pre-wrap; 
              word-wrap: break-word;
              white-space: pre-wrap; 
              white-space: -moz-pre-wrap; 
              white-space: -pre-wrap; width:300px">{!! str_limit($product->description, 600, ' ...') !!}</td>
              <td style="width:40px"> 
                
                <div class="row">
                    <a href="{{route('shops', $product->id)}}" class="btn btn-warning btn-fw">View</a>
                </div>
                <br>
                <div class="row">
                    <a href="{{route('product.edit', $product->id)}}" class="btn btn-warning btn-fw">Update</a>
                </div>
                <br>
                <div class="row">
                    <form action="{{route('product.delete', $product->id)}}" method="POST" enctype="multipart/form-data">
                        {{csrf_field()}}
                        {{method_field('DELETE')}}
                        <input type="submit" value="Delete" class="btn btn-danger  btn-fw">
                    </form>
                </div>
              </td>
            </tr>
            @endforeach
            
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>



     
@endsection

resources/views/admin/products/upload.blade.php
@extends('admin.layouts.main')
@section('title', 'Upload Image Product')
@section('tinymce')
    @include('admin.layouts.partials.tinymce')
@endsection
@include('sweetalert::alert')

@section('content')

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">New Product</h4>
                <p class="card-description"></p>
                    <form action="{{route('upload.images', $product->id)}}" method="post" class="dropzone" id="my-awesome-dropzone-{{$product->id}}">
                        {{csrf_field()}}
                      <input type="file" name="file" >
                    </form>
            </div>
        </div>
    </div>
</div>
    

@endsection